/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.LoyaltyProgramOffers.con;
import static shoppingmall.LoyaltyProgramOffers.connectionUrl;
import static shoppingmall.LoyaltyProgramOffers.stmt;
import static shoppingmall.MainMenu.username;
import static shoppingmall.ViewLostItems.username;

/**
 *
 * @author MH
 */
public class Giftcard extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static java.sql.Statement stmt = null;

    
    /**
     * Creates new form Giftcard
     */
    
    public static String username=null;
    
    public Giftcard() {
        initComponents();
         setSize(800,555);
        connectDb();
        ListUsers ();
    }
    
    public Giftcard(String myusername) {
        username = myusername;
        System.out.println("This is ViewlostItems, your username is: "+username);
        initComponents();
         setSize(800,555);
        connectDb();
          ListUsers ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        cashamount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        visitor_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter the cash amount you want to gift:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 250, 17);
        getContentPane().add(cashamount);
        cashamount.setBounds(300, 100, 132, 22);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select the username of the person you want to address this card to:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 430, 17);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Zara", "H&M", "Pull and Bear", "Mango", "Zara Home", "Pandora", "Lush", "Calvin Klein", "Oysho", "Pink", "Nike", "Zadig et Voltaire", "MAC Cosmetics", "KIKO Cosmetics", "H&M Home", "Accessorize", "Parfois", "I am", "Bath and Bbody Works", "Aldo", "Geox", "Charles and Keith" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 160, 264, 146);

        jButton1.setText("Gift");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 320, 51, 25);

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choose your shop sponsors:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 140, 180, 17);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(726, 472, 59, 25);

        jLabel4.setBackground(new java.awt.Color(255, 204, 102));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("GIFTCARD");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 20, 130, 33);

        visitor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Visitor"
            }
        ));
        jScrollPane2.setViewportView(visitor_table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 160, 180, 237);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/46.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 850, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuyGiftcard();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HelpdeskMenu hmenu = new HelpdeskMenu(username);
        hmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giftcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giftcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giftcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giftcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giftcard().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void ListUsers () {
        try {
            DefaultTableModel model = (DefaultTableModel) visitor_table.getModel();
            model.setRowCount(0);
            String query = "SELECT visitor_username " +
                            "FROM visitor";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) { 
                String user = rs.getString(1);
                model = (DefaultTableModel) visitor_table.getModel();
                model.addRow(new Object[]{user});
                visitor_table.setModel(model);
            }  
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void BuyGiftcard() {
        try{
            int serviceid=-1;
            String mycash_str = null;
            String query = "SELECT cash_balance " +
                            "FROM visitor " + 
                            "WHERE visitor_username = '" + username + "'";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                mycash_str = rs.getString(1);
            }  
            float mycash = Float.valueOf(mycash_str);
            
            String cash_amount_str = cashamount.getText();
            float cash_amount = Float.valueOf(cash_amount_str);

            if (cash_amount > mycash) {
                JOptionPane optionPane = new JOptionPane("You do not have enough cash to buy a giftcard.");
                JDialog dialog = optionPane.createDialog("WARNING!");
                dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
                dialog.setVisible(true);
                return;
            }
            else {
                JOptionPane optionPane = new JOptionPane("You have successfuly bought a giftcard!");
                JDialog dialog = optionPane.createDialog("SUCCESS!");
                dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
                dialog.setVisible(true);
            }
            
            int row = visitor_table.getSelectedRow();
            String giftee_username = visitor_table.getModel().getValueAt(row, 0).toString();
            query = "SELECT service_id " +
                            "FROM helpdesk";
            
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                serviceid = rs.getInt(1);
            }
            
            String insert = "INSERT INTO helpdesk (service_type) VALUES ('giftcard')";  
            int temp = stmt.executeUpdate(insert);
        
            insert = "INSERT INTO giftcard (service_id, cash_amount, gifter_username, giftee_username) VALUES " +
                     "(" + serviceid + ", " + cash_amount + ", '" + username + "', '" + giftee_username + "')";         
            temp = stmt.executeUpdate(insert);
            
            int[] selectedIndices = jList1.getSelectedIndices();
            String[] myArray = new String[50];
            for (int i = 0; i < selectedIndices.length; i++) {
                if (String.valueOf(jList1.getModel().getElementAt(selectedIndices[i]))==null)
                    break;
                myArray[i] =  String.valueOf(jList1.getModel().getElementAt(selectedIndices[i]));
                insert = "INSERT INTO giftcard_shop_sponsors VALUES " +
                         "(" + serviceid + ",'" + myArray[i] + "')";
                temp = stmt.executeUpdate(insert);
            }

            String update = "UPDATE visitor " +
                    "SET cash_balance = cash_balance - " + cash_amount + " " +
                    "WHERE visitor_username = '" + username + "' AND cash_balance >= " + cash_amount;
            temp = stmt.executeUpdate(update);
            
            update = "UPDATE visitor " +
                    "SET cash_balance = cash_balance + " + cash_amount + " " +
                    "WHERE visitor_username = '" + giftee_username + "'";
            temp = stmt.executeUpdate(update);
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cashamount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable visitor_table;
    // End of variables declaration//GEN-END:variables
}
