/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.HelpdeskMenu.username;
import static shoppingmall.LoyaltyProgramOffers.con;
import static shoppingmall.LoyaltyProgramOffers.connectionUrl;
import static shoppingmall.LoyaltyProgramOffers.stmt;
import static shoppingmall.MainMenu.username;

/**
 *
 * @author MH
 */
public class LostFound extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static java.sql.Statement stmt = null;

    /**
     * Creates new form Helpdesk
     */
    
    public static String username=null;
    
    public LostFound() {
        initComponents();
         setSize(540,413);
        connectDb();
    }
    
    public LostFound(String myusername) {
        username = myusername;
        System.out.println("This is Helpdesk, your username is: "+username);
        initComponents();
         setSize(540,413);
        connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        facilitytype_comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        itemfound = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        facilitytype_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurant", "Shop", "Cinema", "Kids Playground", "Parking", "Other" }));
        getContentPane().add(facilitytype_comboBox);
        facilitytype_comboBox.setBounds(194, 132, 216, 22);

        jLabel1.setText("I have found this item at:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 135, 144, 16);
        getContentPane().add(itemfound);
        itemfound.setBounds(194, 79, 216, 22);

        jLabel3.setText("Item found:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 82, 67, 16);
        getContentPane().add(year);
        year.setBounds(23, 239, 69, 22);

        jLabel4.setText("Enter the date in which the item was found in format (YYYY-MM-DD):");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 185, 395, 16);
        getContentPane().add(month);
        month.setBounds(129, 239, 70, 22);
        getContentPane().add(day);
        day.setBounds(230, 239, 70, 22);

        jLabel5.setText("Year (YYYY)");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 214, 68, 16);

        jLabel6.setText("Month (MM)");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(129, 214, 69, 16);

        jLabel7.setText("Day (DD)");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 214, 51, 16);

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(325, 238, 85, 25);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 297, 59, 25);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ADD LOST AND FOUND ITEM");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 350, 33);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\CMPS Images\\45.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 540, 413);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddLostFound();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HelpdeskMenu hmenu = new HelpdeskMenu(username);
        hmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LostFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LostFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LostFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LostFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LostFound().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void AddLostFound() {
        try{
            int serviceid=-1;
            String lost_at_facility_type = null;
            String insert = "INSERT INTO helpdesk (service_type) VALUES ('lost found')";  
            int temp = stmt.executeUpdate(insert);
            
            String item_type = itemfound.getText();
            Object selectedItem = facilitytype_comboBox.getSelectedItem();
            if (selectedItem != null) 
                lost_at_facility_type = selectedItem.toString();
                        
            String YYYY = year.getText(); 
            String MM = month.getText(); 
            String DD = day.getText(); 
            
            String query = "SELECT service_id " +
                            "FROM helpdesk";
                           
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                serviceid = rs.getInt(1);
            }
            
            insert = "INSERT INTO lost_and_found (service_id, item_type, lost_date, lost_at_facility_type, added_by_user) VALUES " +
                     "(" + serviceid + ", '" + item_type + "', '" + YYYY + "-" + MM + "-" + DD +
                     "', '" + lost_at_facility_type + "', '" + username + "')";
            temp = stmt.executeUpdate(insert);
            
            JOptionPane optionPane = new JOptionPane("You have successfully entered a new lost item!");
            JDialog dialog = optionPane.createDialog("SUCCESS!");
            dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
            dialog.setVisible(true);
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day;
    private javax.swing.JComboBox<String> facilitytype_comboBox;
    private javax.swing.JTextField itemfound;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
