/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import java.io.FileNotFoundException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Scanner;
import java.net.*;
import java.awt.*;
import java.sql.*;
import java.util.Scanner;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.DishSearch.stmt;
import static shoppingmall.DishSearch.username;
import static shoppingmall.HireBabysitter.stmt;
import static shoppingmall.MainMenu.username;
import static shoppingmall.RestaurantMenu.username;

/**
 *
 * @author MH
 */
public class LoyaltyProgramOffers extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static Statement stmt = null;

    /**
     * Creates new form LoyaltyProgramOffers
     */
    public static String username=null;
    
    
    public LoyaltyProgramOffers() {
        initComponents();
        setSize(850,600);
        connectDb();
        ListLoyProgOffers();
    }
    
    public LoyaltyProgramOffers(String myusername) {
        username = myusername;
        System.out.println("This is LoyaltyPrgramOffers, your username is: "+username);
        initComponents();
        setSize(850,600);
        connectDb();
        ListLoyProgOffers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        loyprog_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        offerdesc_textArea = new javax.swing.JTextArea();
        facilityname_textArea = new javax.swing.JTextArea();
        facilitytype_textArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        points = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        loyprog_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Offer ID", "Number of Points"
            }
        ));
        jScrollPane1.setViewportView(loyprog_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(201, 159, 358, 133);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Select an offer ID to retrieve information about the offer then click on the following button:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 360, 553, 17);

        jButton2.setText("Offer Information");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 350, 131, 25);

        offerdesc_textArea.setColumns(20);
        offerdesc_textArea.setRows(5);
        getContentPane().add(offerdesc_textArea);
        offerdesc_textArea.setBounds(72, 449, 164, 26);

        facilityname_textArea.setColumns(20);
        facilityname_textArea.setRows(5);
        getContentPane().add(facilityname_textArea);
        facilityname_textArea.setBounds(507, 447, 164, 28);

        facilitytype_textArea.setColumns(20);
        facilitytype_textArea.setRows(5);
        getContentPane().add(facilitytype_textArea);
        facilitytype_textArea.setBounds(287, 449, 164, 26);

        jLabel2.setText("Description");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 430, 63, 16);

        jLabel3.setText("Facility type");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(287, 430, 67, 16);

        jLabel4.setText("Facility name");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(507, 424, 75, 16);

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Select the offer you want to benefit from and click on the following button:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 310, 456, 14);

        jButton3.setText("Benefit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 310, 71, 25);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(758, 482, 59, 25);

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Are you a loyal customer? Do you have a lot of loyalty points? BENEFIT!");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 50, 650, 22);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("LOYALTY PROGRAM");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(276, 19, 248, 33);

        points.setColumns(20);
        points.setRows(5);
        getContentPane().add(points);
        points.setBounds(381, 104, 164, 30);

        jLabel8.setText("Your number of loyalty points:");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(183, 107, 172, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/50.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 860, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoyProgInfo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BenefitFromOffer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu menu = new MainMenu(username);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoyaltyProgramOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoyaltyProgramOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoyaltyProgramOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoyaltyProgramOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoyaltyProgramOffers().setVisible(true);
            }
        });
      
        
        
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void ListLoyProgOffers() {
        try{
            DefaultTableModel model = (DefaultTableModel) loyprog_table.getModel();
            model.setRowCount(0);
            String query = "SELECT offer_id, nb_points " +
                            "FROM loy_prog_offers " + 
                            "ORDER BY nb_points ASC";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String offer_id = rs.getString(1);
                String nb_points = rs.getString(2);
                model = (DefaultTableModel) loyprog_table.getModel();
                model.addRow(new Object[]{offer_id, nb_points});
                loyprog_table.setModel(model);
            }
            query = "SELECT loyalty_points " +
                            "FROM visitor " + 
                            "WHERE visitor_username = '" + username + "'";
            rs = stmt.executeQuery(query); 
            while (rs.next()) {
                String pts = rs.getString(1);
                points.setText(pts);
            } 
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void LoyProgInfo() {
        try{
            int row = loyprog_table.getSelectedRow();
            String offer_id = loyprog_table.getModel().getValueAt(row, 0).toString();
            String query = "SELECT offer_description, facility_type, facility_name " +
                            "FROM loy_prog_offers " + 
                            "WHERE offer_id = " + offer_id;
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String offer_description = rs.getString(1);
                offerdesc_textArea.setText(offer_description);
                String facility_type = rs.getString(2);
                facilitytype_textArea.setText(facility_type);
                String facility_name = rs.getString(3);
                facilityname_textArea.setText(facility_name);
            } 
           
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void BenefitFromOffer() {
        try{
            String nb_of_points = null, loyalty_points = null;
            int row = loyprog_table.getSelectedRow();
            String offer_id = loyprog_table.getModel().getValueAt(row, 0).toString();
            String query = "SELECT nb_points " +
                            "FROM loy_prog_offers " + 
                            "WHERE offer_id = " + offer_id;
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                nb_of_points = rs.getString(1);
            }  
            int pointsneeded = Integer.parseInt(nb_of_points);

            query = "SELECT loyalty_points " +
                            "FROM visitor " + 
                            "WHERE visitor_username = '" + username + "'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                loyalty_points = rs.getString(1);
            }
            int mypoints = Integer.parseInt(loyalty_points);
            
            if (pointsneeded > mypoints) {
                JOptionPane optionPane = new JOptionPane("You do not have enough loyalty points to benefit from this offer.");
                JDialog dialog = optionPane.createDialog("WARNING!");
                dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
                dialog.setVisible(true);
                return;
            }
            
            query = "SELECT visitor_username " +
                        "FROM benefit_from_offers " + 
                        "WHERE visitor_username = '" + username + "' AND offer_id = " + offer_id;
            rs = stmt.executeQuery(query);
            int count2=0;
            String hasrated=null;
            while (rs.next()) {
                hasrated = rs.getString(1);
                System.out.println(hasrated);
                if (hasrated.equals(username))
                {
                    count2++;
                }
            }

            if (count2==1) {
                JOptionPane optionPane = new JOptionPane("You cannot benefit from an offer twice.");
                JDialog dialog = optionPane.createDialog("WARNING!");
                dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
                dialog.setVisible(true);
                return;
            }
            else {
                JOptionPane optionPane = new JOptionPane("You have successfuly benefited from this offer!");
                JDialog dialog = optionPane.createDialog("SUCCESS!");
                dialog.setAlwaysOnTop(this.isAlwaysOnTopSupported());
                dialog.setVisible(true);
            }
            String update = "UPDATE visitor " +
                    "SET loyalty_points = loyalty_points - " + pointsneeded + " " +
                    "WHERE visitor_username = '" + username + "' AND loyalty_points >= " + pointsneeded;
            int temp = stmt.executeUpdate(update);
            
            String insert = "INSERT INTO benefit_from_offers VALUES " +
                            "('" + username + "', " + offer_id + ")";
            temp = stmt.executeUpdate(insert);
            ListLoyProgOffers();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea facilityname_textArea;
    private javax.swing.JTextArea facilitytype_textArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loyprog_table;
    private javax.swing.JTextArea offerdesc_textArea;
    private javax.swing.JTextArea points;
    // End of variables declaration//GEN-END:variables
}
