/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static shoppingmall.SeasonalEvents.username;
import static shoppingmall.UserFrame.connectionUrl;
import static shoppingmall.UserFrame.stmt;

/**
 *
 * @author Hp
 */
public class MainMenu extends javax.swing.JFrame {
        public static String connectionUrl;
        public static Connection con = null;
        public static java.sql.Statement stmt = null;
    /**
     * Creates new form MainMenu
     */
        
    public static String username=null;
    
    public MainMenu(String myusername) {
        username = myusername;
        System.out.println("This is MainMenu, your username is: "+username);
        initComponents();
        setSize(768,540);
        connectDb();
    }
    
    public MainMenu() {
        initComponents();
        setSize(768,540);
        connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Restaurant = new javax.swing.JButton();
        Shops = new javax.swing.JButton();
        SeasonalEvents = new javax.swing.JButton();
        KidsPlayground = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Restaurant.setText("RESTAURANTS");
        Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantActionPerformed(evt);
            }
        });
        getContentPane().add(Restaurant);
        Restaurant.setBounds(110, 140, 145, 25);

        Shops.setText("SHOPS");
        Shops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopsActionPerformed(evt);
            }
        });
        getContentPane().add(Shops);
        Shops.setBounds(110, 200, 145, 25);

        SeasonalEvents.setText("SEASONAL EVENTS");
        SeasonalEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonalEventsActionPerformed(evt);
            }
        });
        getContentPane().add(SeasonalEvents);
        SeasonalEvents.setBounds(300, 140, 145, 25);

        KidsPlayground.setText("KIDS PLAYGROUND");
        KidsPlayground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KidsPlaygroundActionPerformed(evt);
            }
        });
        getContentPane().add(KidsPlayground);
        KidsPlayground.setBounds(110, 340, 145, 25);

        jButton1.setText("CINEMA MOVIES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 270, 145, 25);

        jButton2.setText("HELPDESK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 270, 145, 25);

        jButton3.setText("LOYALTY PROGRAM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 200, 145, 25);

        jButton4.setText("PARKING");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 340, 145, 25);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Dicover our main facilities");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 90, 240, 22);

        jButton5.setText("ADD CASH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(540, 270, 134, 25);

        jButton6.setText("CHECK PAYMENTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(540, 200, 140, 25);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("MAIN MENU");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 30, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AND HAPPY SHOPPING!");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 410, 300, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/3.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 0, 768, 512);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantActionPerformed
        // TODO add your handling code here:
        RestaurantMenu restmen = new RestaurantMenu(username);
        restmen.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_RestaurantActionPerformed

    private void ShopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopsActionPerformed
        // TODO add your handling code here:
        ShopMenu shopmen = new ShopMenu(username);
        shopmen.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_ShopsActionPerformed

    private void SeasonalEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonalEventsActionPerformed
        // TODO add your handling code here:    
        SeasonalEventMenu semenu = new SeasonalEventMenu(username);
        semenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_SeasonalEventsActionPerformed

    private void KidsPlaygroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KidsPlaygroundActionPerformed
        // TODO add your handling code here:
        PlaygroundMenu pmenu = new PlaygroundMenu(username);
        pmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_KidsPlaygroundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MovieMenu mmenu = new MovieMenu(username);
        mmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HelpdeskMenu hmenu = new HelpdeskMenu(username);
        hmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LoyaltyProgramOffers lpo = new LoyaltyProgramOffers(username);
        lpo.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Parking p = new Parking(username);
        p.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AddCash up = new AddCash(username);
        up.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        UserPaymentInfo up = new UserPaymentInfo(username);
        up.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KidsPlayground;
    private javax.swing.JButton Restaurant;
    private javax.swing.JButton SeasonalEvents;
    private javax.swing.JButton Shops;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
