/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import static shoppingmall.MovieSearch.con;
import static shoppingmall.MovieSearch.connectionUrl;
import static shoppingmall.MovieSearch.stmt;
import static shoppingmall.ShopsList.stmt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.MainMenu.username;
import static shoppingmall.MovieRating.username;

/**
 *
 * @author MH
 */
public class MovieMerchandise extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static Statement stmt = null;

    /**
     * Creates new form MovieMerchandise
     */
    
    public static String username=null;
    
    public MovieMerchandise() {
        initComponents();
        setSize(650,430);
        connectDb();
        MerchListbyMovie();
    }
    
    public MovieMerchandise(String myusername) {
        username = myusername;
        System.out.println("This is MovieMErchandise, your username is: "+username);        
        initComponents();
        setSize(650,430);
        connectDb();
        MerchListbyMovie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        merchinfo_table = new javax.swing.JTable();
        mov_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        merchinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop Name", "Item ID", "Movie"
            }
        ));
        jScrollPane1.setViewportView(merchinfo_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 123, 452, 170);

        mov_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mov_nameKeyTyped(evt);
            }
        });
        getContentPane().add(mov_name);
        mov_name.setBounds(100, 83, 159, 22);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter the name of your favorite movie and see if its merchandise is sold at our stores!");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 530, 17);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 348, 59, 25);

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("MOVIE MERCHANDISE");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 280, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/43.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 650, 421);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mov_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mov_nameKeyTyped
        // TODO add your handling code here:
        MerchListbyMovie();
    }//GEN-LAST:event_mov_nameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MovieMenu mmenu = new MovieMenu(username);
        mmenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieMerchandise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieMerchandise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieMerchandise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieMerchandise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieMerchandise().setVisible(true);
            }
        });
    }
    
    private void connectDb() {
    try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }

    
    private void MerchListbyMovie(){
        try{
            DefaultTableModel model = (DefaultTableModel) merchinfo_table.getModel();
            model.setRowCount(0);
            String moviename = mov_name.getText();
            String query = "SELECT shop_name, item_id, movie_title FROM movie_merchandise WHERE movie_title LIKE'"+moviename+"%'";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String shop_name = rs.getString(1);
                String item_id = rs.getString(2);
                String movie_title = rs.getString(3);
                model = (DefaultTableModel) merchinfo_table.getModel();
                model.addRow(new Object[]{shop_name, item_id, movie_title});
                merchinfo_table.setModel(model);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable merchinfo_table;
    private javax.swing.JTextField mov_name;
    // End of variables declaration//GEN-END:variables
}
