/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.net.*;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static shoppingmall.UserFrame.con;
import static shoppingmall.UserFrame.connectionUrl;
import static shoppingmall.UserFrame.stmt;

/**
 *
 * @author Hp
 */

public class Register extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static java.sql.Statement stmt = null;

    /**
     * Creates new form Register
     */
    public static boolean isNumeric(String strNum) {
    if (strNum == null) {
        return false;
    }
    try {
        double d = Double.parseDouble(strNum);
    } catch (NumberFormatException nfe) {
        return false;
    }
    return true;
    }

    public Register() {
        initComponents();
        setSize(765,467);
        connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        FirstnameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        UsernameText = new javax.swing.JTextField();
        MaleCheck = new javax.swing.JCheckBox();
        FemaleCheck = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        DayText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MonthText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        YearText = new javax.swing.JTextField();
        PhoneText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CityText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        StreetText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CashText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(670, 390, 75, 25);

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(590, 350, 81, 25);

        jLabel1.setText("First name:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 71, 16);

        jLabel2.setText("Last name:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 71, 16);

        jLabel3.setText("Username:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 71, 16);

        jLabel4.setText("Password:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 70, 16);

        jLabel5.setText("Gender:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 320, 50, 16);

        jLabel6.setText("Date of birth");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 70, 71, 16);

        jLabel7.setText("Phone number:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 190, 88, 16);
        getContentPane().add(PasswordText);
        PasswordText.setBounds(160, 240, 170, 22);
        getContentPane().add(FirstnameText);
        FirstnameText.setBounds(160, 90, 170, 22);
        getContentPane().add(LastNameText);
        LastNameText.setBounds(160, 140, 170, 22);
        getContentPane().add(UsernameText);
        UsernameText.setBounds(160, 190, 170, 22);

        MaleCheck.setText("Male");
        MaleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleCheckActionPerformed(evt);
            }
        });
        getContentPane().add(MaleCheck);
        MaleCheck.setBounds(170, 320, 77, 25);

        FemaleCheck.setText("Female");
        FemaleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleCheckActionPerformed(evt);
            }
        });
        getContentPane().add(FemaleCheck);
        FemaleCheck.setBounds(170, 360, 77, 25);

        jLabel8.setText("Day (DD):");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(610, 100, 56, 16);
        getContentPane().add(DayText);
        DayText.setBounds(610, 120, 67, 22);

        jLabel9.setText("Month (MM):");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 100, 78, 16);
        getContentPane().add(MonthText);
        MonthText.setBounds(490, 120, 67, 22);

        jLabel10.setText("Year (YYYY):");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 100, 73, 16);
        getContentPane().add(YearText);
        YearText.setBounds(390, 120, 67, 22);
        getContentPane().add(PhoneText);
        PhoneText.setBounds(500, 180, 170, 22);

        jLabel11.setText("City:");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 220, 30, 16);
        getContentPane().add(CityText);
        CityText.setBounds(500, 220, 170, 22);

        jLabel12.setText("Street:");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 260, 40, 16);
        getContentPane().add(StreetText);
        StreetText.setBounds(500, 260, 170, 22);

        jLabel13.setText("Cash:");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 300, 36, 16);
        getContentPane().add(CashText);
        CashText.setBounds(500, 300, 170, 22);

        jLabel15.setBackground(new java.awt.Color(255, 204, 102));
        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("REGISTER");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 20, 120, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/2.jpg"))); // NOI18N
        jLabel14.setText("REGISTER");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 820, 432);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleCheckActionPerformed
        // TODO add your handling code here:
        FemaleCheck.setSelected(false);
    }//GEN-LAST:event_MaleCheckActionPerformed

    private void FemaleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleCheckActionPerformed
        // TODO add your handling code here:
        MaleCheck.setSelected(false);
    }//GEN-LAST:event_FemaleCheckActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        UserFrame menu = new UserFrame();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        Register();           
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void Register() {
        boolean checkY= isNumeric(YearText.getText());
        boolean checkD=isNumeric(DayText.getText());
        boolean checkM=isNumeric(MonthText.getText());
        boolean check = (!MaleCheck.isSelected())&&(!MaleCheck.isSelected());
        if (FirstnameText.getText().trim().isEmpty()||LastNameText.getText().trim().isEmpty()||UsernameText.getText().trim().isEmpty()||PasswordText.getText().trim().isEmpty()||YearText.getText().trim().isEmpty()||DayText.getText().trim().isEmpty()||MonthText.getText().trim().isEmpty()||check){
              JOptionPane.showMessageDialog(null, "Missing info.");  
        } else if(!(checkY)||!(checkD)||!(checkM)) {
              JOptionPane.showMessageDialog(null, "Please enter a valid date."); 
        }
        else {
            try {
                String query= "Select * from visitor where visitor_username='"+UsernameText.getText()+"'";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()){
                   JOptionPane.showMessageDialog(null, "This username already exists. Please choose another one."); 
                   return;
                }
                else {
                    String Gender;
                    if (MaleCheck.isSelected()){
                        Gender="Male";   
                    }
                    else {
                        Gender="Female";
                    }
                    String City;
                    String Street;
                    String Cash;
                    String Phone;
                    if (CityText.getText().trim().isEmpty()){
                        City="NULL";
                    }
                    else{
                        City="'"+CityText.getText()+"'";
                    }
                    if (StreetText.getText().trim().isEmpty()){
                        Street="NULL";
                    }
                    else{
                        Street="'"+StreetText.getText()+"'";
                    }
                    if (CashText.getText().trim().isEmpty()){
                        Cash="NULL";
                    }
                    else{
                        Cash=CashText.getText();
                    }
                    if (PhoneText.getText().trim().isEmpty()){
                        Phone="NULL";
                    }
                    else{
                        Phone="'"+PhoneText.getText()+"'";
                    }
                    String Birthdate=YearText.getText()+"-"+MonthText.getText()+"-"+DayText.getText();
                    String insert= "INSERT INTO visitor VALUES('"+UsernameText.getText()+"','"+PasswordText.getText()+"','"+FirstnameText.getText()+"','"+LastNameText.getText()+"','"+Gender+"','"+Birthdate+"',"+Phone+","+City+","+Street+",NULL,"+Cash+")";
                    stmt.executeUpdate(insert);
                    JOptionPane.showMessageDialog(null, "Your user was successfully created. Enjoy your visits!");
                    UserFrame menu = new UserFrame();
                    menu.setVisible(true);
                    setVisible(false); 
                }   
    
        } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CashText;
    private javax.swing.JTextField CityText;
    private javax.swing.JTextField DayText;
    private javax.swing.JCheckBox FemaleCheck;
    private javax.swing.JTextField FirstnameText;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JCheckBox MaleCheck;
    private javax.swing.JTextField MonthText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField StreetText;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JTextField YearText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
