/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.net.*;
import java.awt.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.MainMenu.username;


/**
 *
 * @author Hp
 */
public class Restaurant extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static java.sql.Statement stmt = null;

    /**
     * Creates new form Restaurant
     */
    
    
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    public static String username=null;
    
    public Restaurant(String myusername) {
        username = myusername;
        System.out.println("This is Restaurant, your username is: "+username);
        initComponents();
        setSize(960,590);
        connectDb();
        RestaurantListbyName();
    }
    
    public Restaurant() {
        initComponents();
        setSize(960,590);
        connectDb();
        RestaurantListbyName();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        restaurantinfo_table = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        location = new javax.swing.JTextArea();
        phone = new javax.swing.JTextArea();
        openingtime = new javax.swing.JTextArea();
        closingtime = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        restaurantinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Cuistine Type"
            }
        ));
        restaurantinfo_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantinfo_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(restaurantinfo_table);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 60, 452, 193);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "Italian", "Japanese", "French", "Lebanese", "Mexican", "Chinese" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 290, 123, 22);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("You can filter the restaurants by choosing the cuisine of you choice:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 290, 420, 17);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 290, 75, 25);

        location.setColumns(20);
        location.setRows(5);
        getContentPane().add(location);
        location.setBounds(140, 420, 164, 25);

        phone.setColumns(20);
        phone.setRows(5);
        getContentPane().add(phone);
        phone.setBounds(140, 510, 164, 28);

        openingtime.setColumns(20);
        openingtime.setRows(5);
        getContentPane().add(openingtime);
        openingtime.setBounds(380, 420, 164, 28);

        closingtime.setColumns(20);
        closingtime.setRows(5);
        getContentPane().add(closingtime);
        closingtime.setBounds(380, 510, 164, 25);

        jLabel2.setText("Location");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 390, 47, 16);

        jLabel3.setText("Phone number");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 480, 83, 16);

        jLabel4.setText("Opening time");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 390, 76, 20);

        jLabel5.setText("Closing time");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 480, 70, 16);

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("RESTAURANTS");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 20, 180, 33);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("To retrieve information about a restaurant, please click on its name in the table above.");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 340, 530, 17);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 520, 59, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/9.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RestaurantListByCuisine();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void restaurantinfo_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantinfo_tableMouseClicked
        // TODO add your handling code here:
        RestaurantInfo();
    }//GEN-LAST:event_restaurantinfo_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RestaurantMenu restmen = new RestaurantMenu(username);
        restmen.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void RestaurantListbyName(){
        try{
            DefaultTableModel model = (DefaultTableModel) restaurantinfo_table.getModel();
            model.setRowCount(0);
            String query = "SELECT restaurant_name, cuisine_type FROM restaurant ORDER BY restaurant_name";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String shop_name = rs.getString(1);
                String cuisine_type = rs.getString(2);
                model = (DefaultTableModel) restaurantinfo_table.getModel();
                model.addRow(new Object[]{shop_name, cuisine_type});
                restaurantinfo_table.setModel(model);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void RestaurantListByCuisine() {
        try{
            DefaultTableModel model = (DefaultTableModel) restaurantinfo_table.getModel();
            model.setRowCount(0);
            String chosencat=null;
            Object selectedItem = jComboBox1.getSelectedItem();
            if (selectedItem != null) 
                chosencat = selectedItem.toString();
            String query = "SELECT restaurant_name, cuisine_type FROM restaurant WHERE cuisine_type = '" + chosencat + "' ORDER BY restaurant_name";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String shop_name = rs.getString(1);
                String category = rs.getString(2);
                model = (DefaultTableModel) restaurantinfo_table.getModel();
                model.addRow(new Object[]{shop_name, category});
                restaurantinfo_table.setModel(model);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void RestaurantInfo(){
        try{
            int row = restaurantinfo_table.getSelectedRow();
            String restchosen = restaurantinfo_table.getModel().getValueAt(row, 0).toString();

            String query = "SELECT location, phone, opening_time, closing_time FROM restaurant WHERE restaurant_name = '" + restchosen + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String shoploc = rs.getString(1);
                location.setText(shoploc);
                String shopphone = rs.getString(2);
                phone.setText(shopphone);
                String optime = rs.getString(3);
                openingtime.setText(optime);
                String cltime = rs.getString(4);
                closingtime.setText(cltime);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea closingtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea location;
    private javax.swing.JTextArea openingtime;
    private javax.swing.JTextArea phone;
    private javax.swing.JTable restaurantinfo_table;
    // End of variables declaration//GEN-END:variables
}
