/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;


import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.RemoveItemReservation.username;

/**
 *
 * @author Ahmad Mourad
 */
public class ShopsList extends javax.swing.JFrame {
    public static String connectionUrl;
    public static Connection con = null;
    public static Statement stmt = null;
    /**
     * Creates new form ShopsList
     */
    
    public static String username=null;
    
    public ShopsList() {
        initComponents();
        setSize(680,475);
        connectDb();
        shopListbyName();
    }
    
    public ShopsList(String myusername) {
        username = myusername;
        System.out.println("This is ShopsList, your username is: "+username);
        initComponents();
        setSize(680,475);
        connectDb();
        shopListbyName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shopsinfo_table = new javax.swing.JTable();
        cat_comboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        location = new javax.swing.JTextArea();
        phone = new javax.swing.JTextArea();
        openingtime = new javax.swing.JTextArea();
        closingtime = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SHOPS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 90, 33);

        shopsinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop Name", "Category"
            }
        ));
        shopsinfo_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopsinfo_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(shopsinfo_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 575, 167);

        cat_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothing", "Home", "Accessories", "Selfcare", "Cosmetics", "Shoes" }));
        getContentPane().add(cat_comboBox);
        cat_comboBox.setBounds(350, 250, 94, 22);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 250, 75, 25);

        location.setColumns(20);
        location.setRows(5);
        getContentPane().add(location);
        location.setBounds(60, 340, 191, 26);

        phone.setColumns(20);
        phone.setRows(5);
        getContentPane().add(phone);
        phone.setBounds(60, 400, 191, 25);

        openingtime.setColumns(20);
        openingtime.setRows(5);
        getContentPane().add(openingtime);
        openingtime.setBounds(320, 340, 206, 26);

        closingtime.setColumns(20);
        closingtime.setRows(5);
        getContentPane().add(closingtime);
        closingtime.setBounds(320, 400, 206, 25);

        jLabel3.setText("Location");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 320, 47, 16);

        jLabel4.setText("Phone");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 380, 35, 16);

        jLabel5.setText("Opening time");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 320, 76, 16);

        jLabel6.setText("Closing time");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 380, 70, 16);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("You can filter shops by a specific category:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 250, 270, 17);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 400, 59, 25);

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("To retrieve information about a shop, please click on its name in the table above.");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 290, 500, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/23.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -60, 680, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        shopListbyCat();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shopsinfo_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopsinfo_tableMouseClicked
        // TODO add your handling code here:
        shopInfo();
    }//GEN-LAST:event_shopsinfo_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:    
        ShopMenu smenu = new ShopMenu(username);
        smenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopsList().setVisible(true);
            }
        });
    }
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void shopListbyName(){
        try{
            DefaultTableModel model = (DefaultTableModel) shopsinfo_table.getModel();
            model.setRowCount(0);
            String query = "SELECT shop_name, category, location, phone, opening_time, closing_time FROM shop ORDER BY shop_name";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String shop_name = rs.getString(1);
                String category = rs.getString(2);

                model = (DefaultTableModel) shopsinfo_table.getModel();
                model.addRow(new Object[]{shop_name, category});
                shopsinfo_table.setModel(model);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void shopListbyCat(){
        try{
            DefaultTableModel model = (DefaultTableModel) shopsinfo_table.getModel();
            model.setRowCount(0);
            String chosencat=null;
            Object selectedItem = cat_comboBox.getSelectedItem();
            if (selectedItem != null) 
                chosencat = selectedItem.toString();
            String query = "SELECT shop_name, category FROM shop WHERE category = '" + chosencat + "' ORDER BY shop_name";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String shop_name = rs.getString(1);
                String category = rs.getString(2);
                model = (DefaultTableModel) shopsinfo_table.getModel();
                model.addRow(new Object[]{shop_name, category});
                shopsinfo_table.setModel(model);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    private void shopInfo(){
        try{
            int column = 0;
            int row = shopsinfo_table.getSelectedRow();
            String shopchosen = shopsinfo_table.getModel().getValueAt(row, column).toString();

            String query = "SELECT location, phone, opening_time, closing_time FROM shop WHERE shop_name = '" + shopchosen + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String shoploc = rs.getString(1);
                location.setText(shoploc);
                String shopphone = rs.getString(2);
                phone.setText(shopphone);
                String optime = rs.getString(1);
                openingtime.setText(optime);
                String cltime = rs.getString(2);
                closingtime.setText(cltime);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cat_comboBox;
    private javax.swing.JTextArea closingtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea location;
    private javax.swing.JTextArea openingtime;
    private javax.swing.JTextArea phone;
    private javax.swing.JTable shopsinfo_table;
    // End of variables declaration//GEN-END:variables
}
