/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmall;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static shoppingmall.AddCash.con;
import static shoppingmall.AddCash.connectionUrl;
import static shoppingmall.AddCash.stmt;
import static shoppingmall.AddCash.username;
import static shoppingmall.LoyaltyProgramOffers.username;
import static shoppingmall.ViewLostItems.stmt;

/**
 *
 * @author MH
 */
public class UserPaymentInfo extends javax.swing.JFrame {
     public static String connectionUrl;
    public static Connection con = null;
    public static java.sql.Statement stmt = null;

    /**
     * Creates new form UserPaymentInfo
     */
    
    public static String username=null;
    
    public UserPaymentInfo() {
        initComponents();
        setSize(620,480);
        connectDb();
        PaymentInfo();
    }
    
    public UserPaymentInfo(String myusername) {
        username = myusername;
        System.out.println("This is PaymentInfo, your username is: "+username);
        initComponents();
        setSize(620,480);
        connectDb();
        PaymentInfo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cinema = new javax.swing.JTextArea();
        giftcard = new javax.swing.JTextArea();
        parking = new javax.swing.JTextArea();
        shop = new javax.swing.JTextArea();
        reservation = new javax.swing.JTextArea();
        onetimevisit = new javax.swing.JTextArea();
        carwash = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        cinema.setColumns(20);
        cinema.setRows(5);
        getContentPane().add(cinema);
        cinema.setBounds(25, 98, 235, 25);

        giftcard.setColumns(20);
        giftcard.setRows(5);
        getContentPane().add(giftcard);
        giftcard.setBounds(25, 362, 235, 26);

        parking.setColumns(20);
        parking.setRows(5);
        getContentPane().add(parking);
        parking.setBounds(342, 191, 222, 25);

        shop.setColumns(20);
        shop.setRows(5);
        getContentPane().add(shop);
        shop.setBounds(342, 98, 222, 25);

        reservation.setColumns(20);
        reservation.setRows(5);
        getContentPane().add(reservation);
        reservation.setBounds(25, 191, 235, 25);

        onetimevisit.setColumns(20);
        onetimevisit.setRows(5);
        getContentPane().add(onetimevisit);
        onetimevisit.setBounds(25, 284, 235, 25);

        carwash.setColumns(20);
        carwash.setRows(5);
        getContentPane().add(carwash);
        carwash.setBounds(342, 284, 222, 25);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(515, 416, 59, 25);

        jLabel1.setText("Cinema");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 75, 50, 16);

        jLabel2.setText("Playground Reservation");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 168, 134, 16);

        jLabel4.setText("One-time visit to the Playground");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 263, 183, 16);

        jLabel5.setText("Giftcard Purchase");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(25, 339, 100, 16);

        jLabel6.setText("Shopping");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(342, 75, 53, 16);

        jLabel7.setText("Parking");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(342, 168, 42, 16);

        jLabel8.setText("Carwash Services");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(342, 263, 102, 16);

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("USER PAYMENT INFO");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(163, 19, 258, 33);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmall/53.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 620, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu menu = new MainMenu(username);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPaymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPaymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPaymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPaymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPaymentInfo().setVisible(true);
            }
        });
    }
    
    private void connectDb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //java.io.File file  = new java.io.File("UserPass.txt");
            //Scanner input = new Scanner (file);
            //String username = input.nextLine();
            //System.out.println(username);
            //String password = input.nextLine();
            //System.out.println(password);
            connectionUrl = "jdbc:mysql://localhost/shoppingmall?serverTimezone=UTC&" + "user=" + "root" + "&password=" + "root";
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
        catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }
    
    private void PaymentInfo() {
        try{
            String query = "SELECT SUM(totalfee) " +
                            "FROM reservation " +
                            "WHERE visit_id= '" + username + "'";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String restotalfee = rs.getString(1);
                reservation.setText(restotalfee);
            }
            query = "SELECT SUM(totalfee) " +
                            "FROM one_time_visitor " +
                            "WHERE visitor_username='" + username + "'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String ontimevistotalfee = rs.getString(1);
                onetimevisit.setText(ontimevistotalfee);
            }
            query = "SELECT SUM(cash_amount) " +
                            "FROM giftcard " +
                            "WHERE gifter_username='" + username + "'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String gifttotal = rs.getString(1);
                giftcard.setText(gifttotal);
            }
            query = "SELECT SUM(nb_hours*fee_hour) " +
                            "FROM parking_ticket " +
                            "WHERE visitor_username='" + username + "'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String parkingtotal = rs.getString(1);
                parking.setText(parkingtotal);
            }
            
            query = "SELECT SUM(i.price) " +
                    "FROM buy_item b, items i  " +
                    "WHERE b.shop_name=i.shop_name AND b.item_id=i.item_id AND b.visitor_username='" + username + "'";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                String shoptotal = rs.getString(1);
                shop.setText(shoptotal);
            }
            query = "SELECT SUM(m.ticket_fee*t.tickets_nb) " +
                    "FROM cinema_movie m, ticket_purchase t  " +
                    "WHERE m.movie_title=t.movie_title AND t.visitor_username='" + username + "'";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                String cinematotal = rs.getString(1);
                cinema.setText(cinematotal);
            }
        
            query = "SELECT SUM(c.type_fee) " +
                    "FROM carwash_services c, wash_visitor_car w  " +
                    "WHERE c.service_type=w.service_type AND w.visitor_username='" + username + "' ";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                String servicetotal = rs.getString(1);
                carwash.setText(servicetotal);
            }
        }
        catch (SQLException e){
            System.out.println("SQL Exception: "+ e.toString());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea carwash;
    private javax.swing.JTextArea cinema;
    private javax.swing.JTextArea giftcard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea onetimevisit;
    private javax.swing.JTextArea parking;
    private javax.swing.JTextArea reservation;
    private javax.swing.JTextArea shop;
    // End of variables declaration//GEN-END:variables
}
